/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AvailabilityStatus = { 'Available' : null } |
  { 'Sold' : null } |
  { 'Used' : null };
export type QualityGrade = { 'Substandard' : null } |
  { 'Standard' : null } |
  { 'Superior' : null };
export interface Sale {
  'saleId' : string,
  'buyerContact' : string,
  'quantitySold' : bigint,
  'salePrice' : number,
  'buyerName' : string,
  'strawId' : string,
  'saleDate' : string,
}
export interface SaleBill {
  'sale' : Sale,
  'straw' : SemenStraw,
  'totalAmount' : number,
}
export interface SemenStraw {
  'status' : AvailabilityStatus,
  'colorCode' : string,
  'quality' : QualityGrade,
  'quantity' : bigint,
  'storageLocation' : string,
  'bullId' : string,
  'collectionDate' : string,
  'strawId' : string,
}
export interface _SERVICE {
  'addOrUpdateStraw' : ActorMethod<
    [string, string, string, QualityGrade, string, bigint, string],
    undefined
  >,
  'createSale' : ActorMethod<
    [string, string, string, string, bigint, number],
    undefined
  >,
  'generateSaleBill' : ActorMethod<[string], [] | [SaleBill]>,
  'getAllSales' : ActorMethod<[], Array<Sale>>,
  'getAllStraws' : ActorMethod<[], Array<SemenStraw>>,
  'getSaleById' : ActorMethod<[string], [] | [Sale]>,
  'getStrawById' : ActorMethod<[string], [] | [SemenStraw]>,
  'transformStrawQuantity' : ActorMethod<[string, bigint], undefined>,
  'updateStrawStatus' : ActorMethod<[string, AvailabilityStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];