/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QualityGrade = IDL.Variant({
  'Substandard' : IDL.Null,
  'Standard' : IDL.Null,
  'Superior' : IDL.Null,
});
export const Sale = IDL.Record({
  'saleId' : IDL.Text,
  'buyerContact' : IDL.Text,
  'quantitySold' : IDL.Nat,
  'salePrice' : IDL.Float64,
  'buyerName' : IDL.Text,
  'strawId' : IDL.Text,
  'saleDate' : IDL.Text,
});
export const AvailabilityStatus = IDL.Variant({
  'Available' : IDL.Null,
  'Sold' : IDL.Null,
  'Used' : IDL.Null,
});
export const SemenStraw = IDL.Record({
  'status' : AvailabilityStatus,
  'quality' : QualityGrade,
  'quantity' : IDL.Nat,
  'storageLocation' : IDL.Text,
  'bullId' : IDL.Text,
  'collectionDate' : IDL.Text,
  'strawId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addOrUpdateStraw' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, QualityGrade, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'createSale' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
  'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getAllStraws' : IDL.Func([], [IDL.Vec(SemenStraw)], ['query']),
  'getSaleById' : IDL.Func([IDL.Text], [IDL.Opt(Sale)], ['query']),
  'getStrawById' : IDL.Func([IDL.Text], [IDL.Opt(SemenStraw)], ['query']),
  'updateStrawStatus' : IDL.Func([IDL.Text, AvailabilityStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QualityGrade = IDL.Variant({
    'Substandard' : IDL.Null,
    'Standard' : IDL.Null,
    'Superior' : IDL.Null,
  });
  const Sale = IDL.Record({
    'saleId' : IDL.Text,
    'buyerContact' : IDL.Text,
    'quantitySold' : IDL.Nat,
    'salePrice' : IDL.Float64,
    'buyerName' : IDL.Text,
    'strawId' : IDL.Text,
    'saleDate' : IDL.Text,
  });
  const AvailabilityStatus = IDL.Variant({
    'Available' : IDL.Null,
    'Sold' : IDL.Null,
    'Used' : IDL.Null,
  });
  const SemenStraw = IDL.Record({
    'status' : AvailabilityStatus,
    'quality' : QualityGrade,
    'quantity' : IDL.Nat,
    'storageLocation' : IDL.Text,
    'bullId' : IDL.Text,
    'collectionDate' : IDL.Text,
    'strawId' : IDL.Text,
  });
  
  return IDL.Service({
    'addOrUpdateStraw' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, QualityGrade, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'createSale' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getAllStraws' : IDL.Func([], [IDL.Vec(SemenStraw)], ['query']),
    'getSaleById' : IDL.Func([IDL.Text], [IDL.Opt(Sale)], ['query']),
    'getStrawById' : IDL.Func([IDL.Text], [IDL.Opt(SemenStraw)], ['query']),
    'updateStrawStatus' : IDL.Func([IDL.Text, AvailabilityStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };