/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SemenStraw {
    status: AvailabilityStatus;
    colorCode: string;
    quality: QualityGrade;
    quantity: bigint;
    storageLocation: string;
    bullId: string;
    collectionDate: string;
    strawId: string;
}
export interface SaleBill {
    sale: Sale;
    straw: SemenStraw;
    totalAmount: number;
}
export interface Sale {
    saleId: string;
    buyerContact: string;
    quantitySold: bigint;
    salePrice: number;
    buyerName: string;
    strawId: string;
    saleDate: string;
}
export enum AvailabilityStatus {
    Available = "Available",
    Sold = "Sold",
    Used = "Used"
}
export enum QualityGrade {
    Substandard = "Substandard",
    Standard = "Standard",
    Superior = "Superior"
}
export interface backendInterface {
    addOrUpdateStraw(strawId: string, bullId: string, collectionDate: string, quality: QualityGrade, storageLocation: string, quantity: bigint, colorCode: string): Promise<void>;
    createSale(strawId: string, saleDate: string, buyerName: string, buyerContact: string, quantitySold: bigint, salePrice: number): Promise<void>;
    generateSaleBill(saleId: string): Promise<SaleBill | null>;
    getAllSales(): Promise<Array<Sale>>;
    getAllStraws(): Promise<Array<SemenStraw>>;
    getSaleById(saleId: string): Promise<Sale | null>;
    getStrawById(strawId: string): Promise<SemenStraw | null>;
    transformStrawQuantity(strawId: string, quantity: bigint): Promise<void>;
    updateStrawStatus(strawId: string, newStatus: AvailabilityStatus): Promise<void>;
}
import type { AvailabilityStatus as _AvailabilityStatus, QualityGrade as _QualityGrade, Sale as _Sale, SaleBill as _SaleBill, SemenStraw as _SemenStraw } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addOrUpdateStraw(arg0: string, arg1: string, arg2: string, arg3: QualityGrade, arg4: string, arg5: bigint, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateStraw(arg0, arg1, arg2, to_candid_QualityGrade_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateStraw(arg0, arg1, arg2, to_candid_QualityGrade_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async createSale(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSale(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSale(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async generateSaleBill(arg0: string): Promise<SaleBill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.generateSaleBill(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateSaleBill(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSales(): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSales();
            return result;
        }
    }
    async getAllStraws(): Promise<Array<SemenStraw>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStraws();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStraws();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSaleById(arg0: string): Promise<Sale | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSaleById(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSaleById(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStrawById(arg0: string): Promise<SemenStraw | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStrawById(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStrawById(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async transformStrawQuantity(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.transformStrawQuantity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformStrawQuantity(arg0, arg1);
            return result;
        }
    }
    async updateStrawStatus(arg0: string, arg1: AvailabilityStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStrawStatus(arg0, to_candid_AvailabilityStatus_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStrawStatus(arg0, to_candid_AvailabilityStatus_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AvailabilityStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvailabilityStatus): AvailabilityStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_QualityGrade_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QualityGrade): QualityGrade {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_SaleBill_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaleBill): SaleBill {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_SemenStraw_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SemenStraw): SemenStraw {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sale]): Sale | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SemenStraw]): SemenStraw | null {
    return value.length === 0 ? null : from_candid_SemenStraw_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SaleBill]): SaleBill | null {
    return value.length === 0 ? null : from_candid_SaleBill_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sale: _Sale;
    straw: _SemenStraw;
    totalAmount: number;
}): {
    sale: Sale;
    straw: SemenStraw;
    totalAmount: number;
} {
    return {
        sale: value.sale,
        straw: from_candid_SemenStraw_n6(_uploadFile, _downloadFile, value.straw),
        totalAmount: value.totalAmount
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AvailabilityStatus;
    colorCode: string;
    quality: _QualityGrade;
    quantity: bigint;
    storageLocation: string;
    bullId: string;
    collectionDate: string;
    strawId: string;
}): {
    status: AvailabilityStatus;
    colorCode: string;
    quality: QualityGrade;
    quantity: bigint;
    storageLocation: string;
    bullId: string;
    collectionDate: string;
    strawId: string;
} {
    return {
        status: from_candid_AvailabilityStatus_n8(_uploadFile, _downloadFile, value.status),
        colorCode: value.colorCode,
        quality: from_candid_QualityGrade_n10(_uploadFile, _downloadFile, value.quality),
        quantity: value.quantity,
        storageLocation: value.storageLocation,
        bullId: value.bullId,
        collectionDate: value.collectionDate,
        strawId: value.strawId
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Substandard: null;
} | {
    Standard: null;
} | {
    Superior: null;
}): QualityGrade {
    return "Substandard" in value ? QualityGrade.Substandard : "Standard" in value ? QualityGrade.Standard : "Superior" in value ? QualityGrade.Superior : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Available: null;
} | {
    Sold: null;
} | {
    Used: null;
}): AvailabilityStatus {
    return "Available" in value ? AvailabilityStatus.Available : "Sold" in value ? AvailabilityStatus.Sold : "Used" in value ? AvailabilityStatus.Used : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SemenStraw>): Array<SemenStraw> {
    return value.map((x)=>from_candid_SemenStraw_n6(_uploadFile, _downloadFile, x));
}
function to_candid_AvailabilityStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvailabilityStatus): _AvailabilityStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_QualityGrade_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QualityGrade): _QualityGrade {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvailabilityStatus): {
    Available: null;
} | {
    Sold: null;
} | {
    Used: null;
} {
    return value == AvailabilityStatus.Available ? {
        Available: null
    } : value == AvailabilityStatus.Sold ? {
        Sold: null
    } : value == AvailabilityStatus.Used ? {
        Used: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QualityGrade): {
    Substandard: null;
} | {
    Standard: null;
} | {
    Superior: null;
} {
    return value == QualityGrade.Substandard ? {
        Substandard: null
    } : value == QualityGrade.Standard ? {
        Standard: null
    } : value == QualityGrade.Superior ? {
        Superior: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
